[package]
name = "like-shell"
version = "0.2.1"
description = "Shell-like utilities for Rust. Useful for E2E tests."
license = "Apache-2.0"
edition = "2021"

[dependencies]
fs_extra = "1.3.0"
libc = "0.2.155"
tempdir = "0.3.7"
